feat: added default fallback image for Card.ImageCap component
openedx/brand-openedx pull request #12
Opened 2023-01-03 07:23 UTC by PKulkoRaccoonGang

2023-01-03 07:23 UTC, openedx-webhooks commented
Thanks for the pull request, @PKulkoRaccoonGang!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-01-06 13:20 UTC, adamstankiewicz requested changes
I might recommend renaming the file to be specific to the `Card.ImageCap` and under a `./paragon/images` folder to make it more evident that the image(s) are for paragon component(s), e.g. card-imagecap-fallback.png

2023-01-06 15:49 UTC, adamstankiewicz approved these changes

2023-01-06 15:49 UTC, merged

2023-01-06 15:49 UTC, openedx-webhooks commented
@PKulkoRaccoonGang 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/brand-openedx&entry.867055334=https://github.com/openedx/brand-openedx/pull/12&entry.1484655318=https://github.com/PKulkoRaccoonGang&entry.752974735=2023-01-03+07:23&entry.1917517419=2023-01-06+15:49&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->

2023-01-06 16:17 UTC, edx-semantic-release commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@edx/brand-openedx/v/1.2.0)
- [GitHub release](https://github.com/openedx/brand-openedx/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: